# Generated by Django 3.0.6 on 2020-06-02 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20200602_0211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
